catch {::common::set_param -quiet hls.xocc.mode csynth};
catch {::common::set_param -quiet hls.xocc.enable_rule_check_client 1};
# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project compute_matrices
set_top compute_matrices
add_files "/home/centos/src/project_data/aws-fpga/SDAccel/examples/xilinx_2018.3/getting_started/host/smith_waterman_3/src/compute_matrices.cpp" -cflags " -g -I /home/centos/src/project_data/aws-fpga/SDAccel/examples/xilinx_2018.3/getting_started/host/smith_waterman_3/src "
open_solution solution
set_part xcvu9p-flgb2104-2-i
create_clock -period 250MHz -name default
config_sdx -target xocc -optimization_level $xocc_optimize_level -profile true
config_dataflow -strict_mode warning
config_debug -enable
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
config_compile -skip_transform
config_export -format ip_catalog -ipname compute_matrices
csynth_design
close_project
puts "Vivado HLS completed successfully"
exit
